### PR TITLE
Add Windows platform support for string streams

### PR DESCRIPTION
**Pull request by tbeu**
See #7

### CODE REVIEW

**Comment by tbeu** [comment]
Are you interested in this PR?
- [ ] Sure, wait.
- [ ] Sorry, don't bother me with that Win stuff.

**Comment by sjoelund** [comment]
I think if this is added, msgpack-c should also be part of the repository (Ubuntu still does not ship 1.0)

**Comment by tbeu** [comment]
Yeah, simply add it. It is only a small number of C files and headers.

**Comment by sjoelund** [comment]
@dietmarw @mtiller how does impact handle git submodule? I assume you use github-generated zip-files, which do not contain these files?

**Comment by tbeu** [comment]
Use KISS: Just copy the files.

**Comment by sjoelund** [comment]
No, that is just stupid when I want to update things :) git subtree is a possibility if submodule is not supported.

**Comment by tbeu** [comment]
Yes, stupid but simple.

**Comment by sjoelund** [comment]
It is sadly not that simple, because the includes in the msgpack-c repository do not work if you do #include "msgpack-c/include/msgpack.h". The reason is that msgpack internally uses:
```#include <msgpack/predef.h>``` - this only works if a -I directive points to the directory containing msgpack...

**Comment by tbeu** [comment]
Why does it not work like this https://github.com/tbeu/msgpack-modelica/tree/issue-12-binaries/MessagePack/Resources/Include for you?

**Comment by sjoelund** [comment]
https://github.com/msgpack/msgpack-c/issues/367 ... might be possible with some weird IncludeDirectory...

**Pull request closed without merging**
