### PR TITLE
Update to msgpack-c 1.0.0

### PR DESCRIPTION
**Pull request by tbeu**
Rename raw to str

### CODE REVIEW

**Comment by tbeu** [comment]
Are you interested in updating?
- [ ] Sure, wait.
- [ ] Sorry, not yet.

**Comment by sjoelund** [comment]
I don't have time to check PR's while I am writing on my thesis. Remind me in a few weeks.

**Comment by tbeu** [comment]
It's time for a reminder :-)

**Comment by tbeu** [comment]
I was preparing a new PR to update to msgpack-c 1.2.0 but noticed that my ols PRs were neither accpeted nor rejected. Now I am in trouble as I simply do not know which old branch I can reuse. Any chance to see these issues resolved?

**Pull request closed without merging**
